### PR TITLE
Update Coveralls Token

### PR DESCRIPTION
**Pull request by llyon-cb**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Tests have been added that prove the fix is effective or that the feature works.
- [x] New and existing tests pass locally with the changes.
- [x] Code follows the style guidelines of this project (PEP8, clean code).
- [x] Linter has passed locally and any fixes were made for failures.
- [x] A self-review of the code has been done.

## Pull request type

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes (not tied to bugs/features)
- [ ] Other (please describe):

## What is the ticket or issue number?

- Ticket Number: N/A

- Issue Number: N/A

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by llyon-cb** [comment]
> Something seems broken still and the status page says response should be back in 6 seconds https://status.coveralls.io/

What do you see that is broken? I see "All Systems Operational" on status.coveralls.io, and the build passing on codeship (https://coveralls.io/jobs/64456623)

**Comment by avanbrunt-cb** [comment]
> > Something seems broken still and the status page says response should be back in 6 seconds https://status.coveralls.io/
> 
> What do you see that is broken? I see "All Systems Operational" on status.coveralls.io, and the build passing on codeship, with successful coverage submission
> (https://coveralls.io/jobs/64456623)

The status is not reporting still

Screen Shot 2020-06-29 at 10 17 36 AM

**Comment by avanbrunt-cb** [comment]
Likely an issue with the fact that Becca created the connection to coveralls for this repo and is now removed from the organization. We may need to delete the coveralls connection and recreate ideally with the carbonblack account or some other org account

**Comment by avanbrunt-cb** [comment]
Closing PR as these changes have been incorporated into the functional test PR. Will look at the coveralls issue in more detail in a separate PR

**Pull request closed without merging**
